sudo: required
services: 
  - docker

before_install:
  - docker build -t charowan/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true charowan/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "MyFirstAWSApp"
  env: "MyFirstAWSApp-env"
  bucket_name: "elasticbeanstalk-eu-north-1-927662313617"
  bucket_path: "MyFirstAWSApp"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"